# Sklearn
sklearn.liner_model\
linear_model:\
RidgeClassifier\
SGDClassifier\
SGDRegressor\
LinearRegression\
LogisticRegression\
Lasso\
etc

документация: http://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model
 , примеры: http://scikit-learn.org/stable/modules/linear_model.html#linear-model

In [4]:
from matplotlib.colors import ListedColormap
from sklearn import cross_validation, datasets, linear_model, metrics

import numpy as np

In [5]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [9]:
boston = datasets.load_boston()


## sklearn.cross_validation

In [34]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(boston.data, boston.target, 
                                                                                     test_size = 0.3)

In [57]:
print 'training sample size: {} objects \n The size of the test sample: {} objects'.format(len(train_data),
                                                                                            len(test_data))

training sample size: 354 objects 
 The size of the test sample: 152 objects


In [58]:
print 'training set:\n', train_data[:5]
print '\n'
print 'The test sample:\n', test_data[:5]

training set:
[[  4.81213000e+00   0.00000000e+00   1.81000000e+01   0.00000000e+00
    7.13000000e-01   6.70100000e+00   9.00000000e+01   2.59750000e+00
    2.40000000e+01   6.66000000e+02   2.02000000e+01   2.55230000e+02
    1.64200000e+01]
 [  1.31100000e-02   9.00000000e+01   1.22000000e+00   0.00000000e+00
    4.03000000e-01   7.24900000e+00   2.19000000e+01   8.69660000e+00
    5.00000000e+00   2.26000000e+02   1.79000000e+01   3.95930000e+02
    4.81000000e+00]
 [  7.05042000e+00   0.00000000e+00   1.81000000e+01   0.00000000e+00
    6.14000000e-01   6.10300000e+00   8.51000000e+01   2.02180000e+00
    2.40000000e+01   6.66000000e+02   2.02000000e+01   2.52000000e+00
    2.32900000e+01]
 [  9.55770000e-01   0.00000000e+00   8.14000000e+00   0.00000000e+00
    5.38000000e-01   6.04700000e+00   8.88000000e+01   4.45340000e+00
    4.00000000e+00   3.07000000e+02   2.10000000e+01   3.06380000e+02
    1.72800000e+01]
 [  1.27346000e+00   0.00000000e+00   1.95800000e+01   1.00000000e

In [59]:
print 'Tags classes on the training set:\n', train_labels
print '\n'
print 'Tags classes on the test sample:\n', test_labels

Tags classes on the training set:
[ 16.4  35.4  13.4  14.8  27.   22.   23.4  50.   20.1  22.8  12.7  21.2
  20.6  16.6  24.4  14.1  13.1  21.6  15.2  29.8  29.6  33.    8.8  15.6
  22.3  23.1  20.6  28.2  14.9  14.5  25.   37.6  20.1  13.6  19.8  20.2
  29.9  21.7  21.7  22.2  26.4  37.2  18.4  19.4  11.7  21.8  23.4  23.1
  18.2  18.   14.   22.2  29.6  21.1  29.4  20.1  17.1  21.7  22.5  11.9
  36.5  21.2  16.7   9.5  13.4  33.3  18.9  23.2  22.   17.1  18.9  36.
  12.8  20.    5.   23.3  14.1  24.1  25.   18.7  13.4  21.   20.4  26.5
  25.   30.5  22.2  17.5   8.8  22.6  23.1  28.7  33.1  50.   21.6  20.9
  10.4  29.   48.5  17.2  21.2  21.7  10.2  22.7  11.8  15.4  23.7  18.6
  22.8  18.5  21.5  31.6  23.9  13.8  15.6  22.   21.1  20.8  32.9  24.8
  19.3  20.9  20.7  14.9  23.8  50.   50.   41.3  50.   12.7   8.3  23.8
  22.9  23.9  21.9  15.   23.3  17.8  17.4  19.6  50.   38.7  36.2  10.2
  31.2  23.6  25.2  24.2  24.6  30.1   6.3  25.1  20.4  13.1  50.   11.
  18.5  13.8  19.3 


## KFold

In [39]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [40]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

[1 4 7 8 9] [0 2 3 5 6]
[0 2 3 5 6] [1 4 7 8 9]


In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

## StratifiedKFold

In [41]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [42]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[1 2 5 8] [0 3 4 6 7 9]
[0 3 4 6 7 9] [1 2 5 8]


## ShuffleSplit

In [43]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

[2 9 3 4 5 8 7 0] [1 6]
[7 5 0 9 2 4 8 6] [1 3]
[9 0 3 4 1 8 2 5] [6 7]
[9 4 3 7 6 2 5 0] [8 1]
[9 7 3 8 2 1 6 5] [0 4]
[3 7 4 1 0 2 6 5] [8 9]
[8 6 2 7 0 5 4 1] [3 9]
[9 2 1 4 0 7 8 6] [3 5]
[9 1 4 5 3 0 2 8] [6 7]
[7 8 6 0 4 5 2 9] [3 1]


## StratifiedShuffleSplit

In [44]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[8 1 9 2 4 7 0 5] [6 3]
[4 3 9 5 6 1 8 2] [0 7]
[2 5 7 9 6 0 3 1] [8 4]
[8 3 7 4 5 1 0 9] [6 2]


## Leave-One-Out

In [45]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


## LinearRegression

In [46]:
linear_regressor = linear_model.LinearRegression()
linear_regressor.fit(train_data, train_labels)
predictions = linear_regressor.predict(test_data)

In [47]:
test_labels

array([ 20.8,  30.1,  34.9,  36.2,  23.2,  24.5,  24.5,  32.7,  24. ,
        15.2,  23.8,  25. ,  28. ,   7.2,  15. ,  18.4,  23.7,  24.1,
        14.3,  18.8,  21.4,  19.4,  18.1,  19.9,  17.8,  44.8,  10.5,
        19.7,  19.4,  33.4,  22.6,  20.1,  16.8,  19.1,  16.1,  26.2,
        12.1,  26.4,  22.6,   8.5,  22.5,  24.4,   8.3,  23.1,  16.1,
        33.2,  35.4,  24.8,  35.1,  17.6,  17.2,  43.5,  18.7,  50. ,
        21.4,  23.7,  41.7,  15.6,  22.4,  39.8,  32. ,  27.5,  24.4,
        14.3,  34.9,  20.3,  27.5,  36.4,  18.5,  19.7,  22.1,  16. ,
         8.7,  23.9,  50. ,  45.4,  42.3,  27.9,  19.5,  10.5,  28.5,
        22.3,  20.3,  13.9,  29.1,  31. ,  14.2,  24.4,  23. ,  18.9,
        12. ,  20.5,  15.6,  13.6,  19.9,  22.9,  34.9,  31.5,  21.4,
        17.7,  16.5,  46.7,  20. ,  31.6,  19.3,   5. ,  14.9,  27.9,
        19.1,  17.8,  34.6,  10.9,  20.3,  15.2,  50. ,   8.5,  19.2,
        20.4,  22.8,  23.7,  13.1,  21.5,  23.8,  43.8,  24.7,  50. ,
        22.5,   7.4,

In [48]:
predictions

array([ 22.45130694,  34.52537733,  34.07228442,  27.42973416,
        17.27010405,  20.59110481,  21.06371958,  29.83013046,
        29.48701433,  19.20378311,  22.03690444,  24.09829702,
        28.34871584,  17.93400442,  15.88040788,  19.38952008,
        27.22376942,  29.96407256,  16.76363061,  20.0545573 ,
        20.15765348,  26.47012548,  17.1527162 ,  17.73558091,
        10.14279279,  37.16220039,  13.42604444,  14.04768138,
        22.84469022,  35.70968275,  26.49617971,  21.12414689,
        21.06900616,  19.09578858,  18.47668278,  23.92952884,
        18.21164788,  22.40454651,  25.86396074,   8.67398823,
        17.48566925,  24.12531154,   9.99873089,  20.73643052,
        18.66492065,  31.24885049,  33.652351  ,  26.09302988,
        34.72571468,  16.17259324,  16.44957581,  38.60850472,
        21.49613778,  24.5135615 ,  22.45490124,  26.12799058,
        36.82556503,  20.75206464,  23.12546383,  33.91790746,
        33.95101101,  24.15860864,  23.75951971,  14.14

In [52]:
metrics.mean_absolute_error(test_labels, predictions)

3.7672057860512527

In [53]:
linear_scoring = cross_validation.cross_val_score(linear_regressor,boston.data, boston.target, scoring = 'mean_absolute_error',cv=10)

In [54]:
print 'mean: {}, std: {}'.format(linear_scoring.mean(), linear_scoring.std())

mean: -4.01035270206, std: 2.08589385191


In [56]:
scorer = metrics.make_scorer(metrics.mean_absolute_error, greater_is_better = True)

In [60]:
linear_scoring = cross_validation.cross_val_score(linear_regressor,boston.data, boston.target, scoring = scorer,cv=10)

In [61]:
print 'mean: {}, std: {}'.format(linear_scoring.mean(), linear_scoring.std())

mean: 4.01035270206, std: 2.08589385191


In [63]:
linear_regressor.coef_

array([ -7.64073944e-02,   7.23902800e-02,   9.35694160e-03,
         3.36368255e+00,  -1.37907284e+01,   3.60807335e+00,
        -4.55541275e-03,  -1.49747981e+00,   3.11578189e-01,
        -1.46126047e-02,  -7.93749015e-01,   9.85689726e-03,
        -5.09457140e-01])

In [65]:
print "y = {:.2f}*x1 + {:.2f}*x2".format(linear_regressor.coef_[0], linear_regressor.coef_[1])

y = -0.08*x1 + 0.07*x2


## lasso

In [66]:
lasso_regressor = linear_model.Lasso(random_state = 3)
lasso_regressor.fit(train_data, train_labels)
lasso_predictions = lasso_regressor.predict(test_data)

In [67]:
lasso_scoring = cross_validation.cross_val_score(lasso_regressor, boston.data, boston.target, scoring = scorer, cv = 10)
print 'mean: {}, std: {}'.format(lasso_scoring.mean(), lasso_scoring.std())

mean: 4.06778358251, std: 1.46740972035


In [68]:
lasso_regressor.coef_

array([-0.04566636,  0.08151087, -0.        ,  0.        , -0.        ,
        0.69977257,  0.01863088, -0.86988759,  0.29959467, -0.01831387,
       -0.6215149 ,  0.00916854, -0.72976437])

In [69]:
print "y = {:.2f}*x1 + {:.2f}*x2".format(lasso_regressor.coef_[0], lasso_regressor.coef_[1])

y = -0.05*x1 + 0.08*x2
